export const STATE_ABBREVIATIONS = {
  'Alabama': 'AL',
  'Alaska': 'AK',
  'American Samoa': 'AS',
  'Arizona': 'AZ',
  'Arkansas': 'AR',
  'California': 'CA',
  'Colorado': 'CO',
  'Connecticut': 'CT',
  'Delaware': 'DE',
  'District Of Columbia': 'DC',
  'Federated States Of Micronesia': 'FM',
  'Florida': 'FL',
  'Georgia': 'GA',
  'Guam': 'GU',
  'Hawaii': 'HI',
  'Idaho': 'ID',
  'Illinois': 'IL',
  'Indiana': 'IN',
  'Iowa': 'IA',
  'Kansas': 'KS',
  'Kentucky': 'KY',
  'Louisiana': 'LA',
  'Maine': 'ME',
  'Marshall Islands': 'MH',
  'Maryland': 'MD',
  'Massachusetts': 'MA',
  'Michigan': 'MI',
  'Minnesota': 'MN',
  'Mississippi': 'MS',
  'Missouri': 'MO',
  'Montana': 'MT',
  'Nebraska': 'NE',
  'Nevada': 'NV',
  'New Hampshire': 'NH',
  'New Jersey': 'NJ',
  'New Mexico': 'NM',
  'New York': 'NY',
  'North Carolina': 'NC',
  'North Dakota': 'ND',
  'Northern Mariana Islands': 'MP',
  'Ohio': 'OH',
  'Oklahoma': 'OK',
  'Oregon': 'OR',
  'Palau': 'PW',
  'Pennsylvania': 'PA',
  'Puerto Rico': 'PR',
  'Rhode Island': 'RI',
  'South Carolina': 'SC',
  'South Dakota': 'SD',
  'Tennessee': 'TN',
  'Texas': 'TX',
  'Utah': 'UT',
  'Vermont': 'VT',
  'Virgin Islands': 'VI',
  'Virginia': 'VA',
  'Washington': 'WA',
  'West Virginia': 'WV',
  'Wisconsin': 'WI',
  'Wyoming': 'WY'
}

export const WEATHER_CODE_TO_IMAGE = {
  200: { day: 'rain_storm', night: 'rain_storm' },
  201: { day: 'rain_storm', night: 'rain_storm' },
  202: { day: 'rain_storm', night: 'rain_storm' },
  210: { day: 'rain_storm', night: 'rain_storm' },
  211: { day: 'thunder_storm', night: 'thunder_storm' },
  212: { day: 'thunder_storm', night: 'thunder_storm' },
  221: { day: 'thunder_storm', night: 'thunder_storm' },
  230: { day: 'rain_storm', night: 'rain_storm' },
  231: { day: 'rain_storm', night: 'rain_storm' },
  232: { day: 'rain_storm', night: 'rain_storm' },
  300: { day: 'rain', night: 'rain' },
  301: { day: 'rain', night: 'rain' },
  302: { day: 'rain', night: 'rain' },
  310: { day: 'rain', night: 'rain' },
  311: { day: 'rain', night: 'rain' },
  312: { day: 'rain', night: 'rain' },
  313: { day: 'rain', night: 'rain' },
  314: { day: 'rain', night: 'rain' },
  321: { day: 'rain', night: 'rain' },
  500: { day: 'rain', night: 'rain' },
  501: { day: 'rain', night: 'rain' },
  502: { day: 'rain', night: 'rain' },
  503: { day: 'rain', night: 'rain' },
  504: { day: 'rain', night: 'rain' },
  511: { day: 'rain', night: 'rain' },
  520: { day: 'rain', night: 'rain' },
  521: { day: 'rain', night: 'rain' },
  522: { day: 'rain', night: 'rain' },
  531: { day: 'rain', night: 'rain' },
  600: { day: 'snow', night: 'snow' },
  601: { day: 'snow', night: 'snow' },
  602: { day: 'snow', night: 'snow' },
  611: { day: 'snow', night: 'snow' },
  612: { day: 'snow', night: 'snow' },
  613: { day: 'snow', night: 'snow' },
  615: { day: 'snow', night: 'snow' },
  616: { day: 'snow', night: 'snow' },
  620: { day: 'snow', night: 'snow' },
  621: { day: 'snow', night: 'snow' },
  622: { day: 'snow', night: 'snow' },
  701: { day: 'fog_cloud', night: 'fog_cloud' },
  711: { day: 'fog_cloud', night: 'fog_cloud' },
  721: { day: 'fog_cloud', night: 'fog_cloud' },
  731: { day: 'fog_cloud', night: 'fog_cloud' },
  741: { day: 'fog_cloud', night: 'fog_cloud' },
  751: { day: 'windy', night: 'windy' },
  761: { day: 'windy', night: 'windy' },
  762: { day: 'fog_cloud', night: 'fog_cloud' },
  771: { day: 'fog_cloud', night: 'fog_cloud' },
  781: { day: 'tornado', night: 'tornado' },
  800: { day: 'clear_day', night: 'clear_night' },
  801: { day: 'partly_cloudy_day', night: 'partly_cloudy_night' },
  802: { day: 'partly_cloudy_day', night: 'partly_cloudy_night' },
  803: { day: 'cloudy', night: 'cloudy' },
  804: { day: 'cloudy', night: 'cloudy' },
}